language: go

sudo: false

go:
  - tip

env:
  global:
    - GOARCH=amd64

install: true

before_script:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - go vet ./...
  - go test -v ./modules/ -covermode=count -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken DrSiX88MGP6WAf4WVN3Rz75wPwhmow9eF

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: false
