language: go

sudo: false

go:
  - 1.6
  - tip

env:
  global:
    - GOARCH=amd64

install: true

#before_script:
#  - rsyslogd &
#  - sleep 1

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go test -v -covermode=count -coverprofile=coverage.out

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci -repotoken DrSiX88MGP6WAf4WVN3Rz75wPwhmow9eF

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: false
