language: go

sudo: false

go:
  - 1.6
  - tip

env:
  global:
    - GOARCH=amd64

install: true

#before_script:
#  - go get github.com/tools/godep

script:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

after_success:
  - goveralls -service=travis-ci -repotoken DrSiX88MGP6WAf4WVN3Rz75wPwhmow9eF

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: false
