language: go

sudo: false
go:
  - 1.6
  - tip
env:
  global:
    - GOARCH=amd64
install: true
#before_script:
#  - rsyslogd &
#  - sleep 1
#script:
#  - make test
#  - ./check-fmt.sh
#  - make deadcode
#  - go get golang.org/x/net/http2/...
#  - ./check-handlers.sh
notifications:
  email:
    on_success: change
    on_failure: always
